//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid Barcrowd = new Guid("3d6da536-3e1b-44a3-8d28-f7d2e7d17350");
		public static readonly Guid Intro = new Guid("e2f1be8d-89a1-4507-ad56-ca51d5005694");
		public static readonly Guid show_time = new Guid("4bfeb2b9-cf2c-4fd5-ba72-ddfef912a69f");

    }
}
